import Link from "next/link";
import { requireRole } from "@/components/app/RoleGuard";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { SectionEyebrow } from "@/components/ui/SectionEyebrow";
import { TypeBadge } from "@/components/app/followup/FollowUpBadges";
import { formatDateTime } from "@/components/app/followup/format";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import {
  countByStatus,
  countPunishmentsByStatus,
  fetchStatsRecords,
} from "@/modules/cadet-followup/infrastructure/queries";
import {
  rankReasons,
  stageTimings,
  summarize,
} from "@/modules/cadet-followup/domain/statistics";
import {
  FOLLOW_UP_STATUS_LABELS,
  FOLLOW_UP_TYPE_LABELS,
  FOLLOW_UP_TYPES,
  PUNISHMENT_STATUSES,
  PUNISHMENT_STATUS_LABELS,
} from "@/modules/cadet-followup/domain/followUp";

export const metadata = { title: "Estatísticas de uso" };
export const dynamic = "force-dynamic";

function Metric({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint?: string;
}) {
  return (
    <div className="rounded-md border border-border bg-card p-3.5">
      <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">
        {label}
      </p>
      <p className="num-mono mt-1 font-display text-2xl font-bold text-foreground">{value}</p>
      {hint && <p className="mt-0.5 text-xs text-muted-foreground">{hint}</p>}
    </div>
  );
}

function hours(value: number | null): string {
  if (value === null) return "—";
  if (value < 1) return `${Math.round(value * 60)} min`;
  return `${value.toFixed(1)} h`;
}

export default async function EstatisticasPage() {
  await requireRole("coordenacao");
  const supabase = createSupabaseServerClient();

  const [records, statusCounts, punishmentCounts] = await Promise.all([
    fetchStatsRecords(supabase),
    countByStatus(supabase),
    countPunishmentsByStatus(supabase),
  ]);

  const summary = summarize(records);
  const ranking = rankReasons(records);
  const timings = stageTimings(records);

  const oldest = records[records.length - 1]?.occurredAt;

  return (
    <div className="mx-auto max-w-3xl space-y-5">
      <div>
        <Link
          href="/coordenacao/acompanhamento"
          className="text-sm text-muted-foreground hover:underline"
        >
          ← Central de acompanhamento
        </Link>
      </div>

      <header>
        <SectionEyebrow>Acompanhamento do cadete</SectionEyebrow>
        <h1 className="font-display text-2xl font-bold">Estatísticas de uso</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Base para decidir a próxima evolução do módulo com dado real — quais motivos
          viram atalho, quais campos sobram e quais etapas estão demorando.
        </p>
      </header>

      {summary.total === 0 ? (
        <Card>
          <CardContent className="p-5 text-sm text-muted-foreground">
            Nenhum registro ainda. Esta tela ganha sentido depois de algumas semanas de uso.
          </CardContent>
        </Card>
      ) : (
        <>
          <p className="rounded-md border border-border bg-secondary/50 px-3.5 py-2.5 text-xs text-muted-foreground">
            {summary.total} registro(s) desde {formatDateTime(oldest)}. Com amostra pequena,
            trate os números como indício, não como conclusão.
          </p>

          <Card>
            <CardHeader>
              <CardTitle>Volume por tipo</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              {FOLLOW_UP_TYPES.map((type) => (
                <Metric
                  key={type}
                  label={FOLLOW_UP_TYPE_LABELS[type]}
                  value={String(summary.byType[type])}
                />
              ))}
              <Metric
                label="Gerados pelo sistema"
                value={String(summary.autoGenerated)}
                hint="ausência de manifestação"
              />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Uso dos campos</CardTitle>
            </CardHeader>
            <CardContent>
              <Metric
                label="Registros com observação"
                value={
                  summary.notesUsageRate === null
                    ? "—"
                    : `${Math.round(summary.notesUsageRate * 100)}%`
                }
                hint="campo opcional — se ficar muito baixo, vale repensá-lo"
              />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Tempo por etapa</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-1 gap-3 sm:grid-cols-3">
              <Metric
                label="Até a manifestação"
                value={hours(timings.averageHoursToManifest)}
                hint={`amostra: ${timings.manifestSample}`}
              />
              <Metric
                label="Até a decisão"
                value={hours(timings.averageHoursToDecide)}
                hint={`amostra: ${timings.decideSample}`}
              />
              <Metric
                label="Prazos vencidos"
                value={String(timings.expiredWithoutManifestation)}
                hint="sem manifestação do cadete"
              />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Motivos mais usados</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border text-left text-[11px] uppercase tracking-[0.12em] text-muted-foreground">
                      <th className="px-4 py-2 font-semibold">Motivo</th>
                      <th className="px-2 py-2 text-right font-semibold">30d</th>
                      <th className="px-2 py-2 text-right font-semibold">7d</th>
                      <th className="px-2 py-2 text-right font-semibold">Total</th>
                      <th className="px-2 py-2 text-right font-semibold">Cadetes</th>
                      <th className="px-4 py-2 text-right font-semibold">Última vez</th>
                    </tr>
                  </thead>
                  <tbody>
                    {ranking.map((item) => (
                      <tr
                        key={`${item.type}-${item.reasonText}`}
                        className="border-b border-border last:border-0"
                      >
                        <td className="px-4 py-2.5">
                          <span className="flex flex-wrap items-center gap-1.5">
                            <TypeBadge type={item.type} />
                            <span className="text-foreground">{item.reasonText}</span>
                          </span>
                        </td>
                        <td className="num-mono px-2 py-2.5 text-right font-semibold">
                          {item.last30Days}
                        </td>
                        <td className="num-mono px-2 py-2.5 text-right text-muted-foreground">
                          {item.last7Days}
                        </td>
                        <td className="num-mono px-2 py-2.5 text-right text-muted-foreground">
                          {item.total}
                        </td>
                        <td className="num-mono px-2 py-2.5 text-right text-muted-foreground">
                          {item.distinctStudents}
                        </td>
                        <td className="num-mono whitespace-nowrap px-4 py-2.5 text-right text-xs text-muted-foreground">
                          {formatDateTime(item.lastUsedAt)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Situação dos registros</CardTitle>
            </CardHeader>
            <CardContent className="space-y-1.5">
              {Object.entries(statusCounts)
                .sort(([, a], [, b]) => b - a)
                .map(([status, count]) => (
                  <div key={status} className="flex items-baseline justify-between gap-3">
                    <span className="text-sm text-muted-foreground">
                      {FOLLOW_UP_STATUS_LABELS[status as keyof typeof FOLLOW_UP_STATUS_LABELS] ??
                        status}
                    </span>
                    <span className="num-mono text-sm font-semibold">{count}</span>
                  </div>
                ))}
            </CardContent>
          </Card>

          {Object.keys(punishmentCounts).length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Cumprimento das punições</CardTitle>
              </CardHeader>
              <CardContent className="space-y-1.5">
                {PUNISHMENT_STATUSES.filter((status) => punishmentCounts[status]).map(
                  (status) => (
                    <div key={status} className="flex items-baseline justify-between gap-3">
                      <span className="text-sm text-muted-foreground">
                        {PUNISHMENT_STATUS_LABELS[status]}
                      </span>
                      <span className="num-mono text-sm font-semibold">
                        {punishmentCounts[status]}
                      </span>
                    </div>
                  ),
                )}
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}
