import { describe, expect, it } from "vitest";
import { rankReasons, stageTimings, summarize, type StatsRecord } from "./statistics";

const NOW = new Date("2026-09-20T12:00:00.000Z");

function record(overrides: Partial<StatsRecord> = {}): StatsRecord {
  return {
    id: crypto.randomUUID(),
    type: "fo_negativo",
    status: "aguardando_manifestacao",
    reasonText: "Coturno sujo",
    reasonId: "r1",
    studentId: "s1",
    hasNotes: false,
    autoGenerated: false,
    occurredAt: "2026-09-19T12:00:00.000Z",
    manifestedAt: null,
    decidedAt: null,
    ...overrides,
  };
}

describe("summarize", () => {
  it("conta por tipo e separa os automáticos", () => {
    const result = summarize([
      record(),
      record({ type: "fo_positivo" }),
      record({ autoGenerated: true }),
      record({ type: "saude" }),
    ]);

    expect(result.total).toBe(4);
    expect(result.byType.fo_negativo).toBe(2);
    expect(result.byType.fo_positivo).toBe(1);
    expect(result.byType.saude).toBe(1);
    expect(result.autoGenerated).toBe(1);
    expect(result.manualNegatives).toBe(1);
  });

  it("mede o uso do campo de observação", () => {
    const result = summarize([record({ hasNotes: true }), record(), record(), record()]);
    expect(result.notesUsageRate).toBe(0.25);
  });

  it("sem registros, não inventa percentual", () => {
    expect(summarize([]).notesUsageRate).toBeNull();
    expect(summarize([]).total).toBe(0);
  });
});

describe("rankReasons", () => {
  it("agrupa por motivo e tipo, ignorando caixa", () => {
    const result = rankReasons(
      [
        record({ reasonText: "Coturno sujo" }),
        record({ reasonText: "coturno SUJO", studentId: "s2" }),
        record({ reasonText: "Falar em forma" }),
      ],
      NOW,
    );

    expect(result).toHaveLength(2);
    expect(result[0]?.reasonText).toBe("Coturno sujo");
    expect(result[0]?.total).toBe(2);
    expect(result[0]?.distinctStudents).toBe(2);
  });

  it("mantém separados o mesmo texto em tipos diferentes", () => {
    const result = rankReasons(
      [
        record({ reasonText: "Destaque", type: "fo_positivo" }),
        record({ reasonText: "Destaque", type: "missao" }),
      ],
      NOW,
    );
    expect(result).toHaveLength(2);
  });

  it("separa a janela recente da histórica", () => {
    const result = rankReasons(
      [
        record({ reasonText: "Atraso", occurredAt: "2026-09-19T12:00:00.000Z" }),
        record({ reasonText: "Atraso", occurredAt: "2026-09-01T12:00:00.000Z" }),
        record({ reasonText: "Atraso", occurredAt: "2026-01-01T12:00:00.000Z" }),
      ],
      NOW,
    );

    expect(result[0]?.total).toBe(3);
    expect(result[0]?.last7Days).toBe(1);
    expect(result[0]?.last30Days).toBe(2);
  });

  it("ordena pelo uso recente, não pelo total histórico", () => {
    const antigo = Array.from({ length: 10 }, () =>
      record({ reasonText: "Motivo antigo", occurredAt: "2026-01-01T12:00:00.000Z" }),
    );
    const recente = Array.from({ length: 3 }, () =>
      record({ reasonText: "Motivo recente", occurredAt: "2026-09-18T12:00:00.000Z" }),
    );

    const result = rankReasons([...antigo, ...recente], NOW);
    expect(result[0]?.reasonText).toBe("Motivo recente");
  });

  it("guarda a última utilização", () => {
    const result = rankReasons(
      [
        record({ occurredAt: "2026-09-10T12:00:00.000Z" }),
        record({ occurredAt: "2026-09-18T12:00:00.000Z" }),
      ],
      NOW,
    );
    expect(result[0]?.lastUsedAt).toBe("2026-09-18T12:00:00.000Z");
  });
});

describe("stageTimings", () => {
  it("mede o tempo até a manifestação e até a decisão", () => {
    const result = stageTimings([
      record({
        occurredAt: "2026-09-19T00:00:00.000Z",
        manifestedAt: "2026-09-19T06:00:00.000Z",
        decidedAt: "2026-09-19T09:00:00.000Z",
        status: "deferido",
      }),
      record({
        occurredAt: "2026-09-19T00:00:00.000Z",
        manifestedAt: "2026-09-19T10:00:00.000Z",
        decidedAt: "2026-09-19T15:00:00.000Z",
        status: "deferido",
      }),
    ]);

    expect(result.averageHoursToManifest).toBe(8);
    expect(result.manifestSample).toBe(2);
    expect(result.averageHoursToDecide).toBe(4);
    expect(result.decideSample).toBe(2);
  });

  it("conta os prazos vencidos sem resposta", () => {
    const result = stageTimings([
      record({ status: "prazo_expirado" }),
      record({ status: "prazo_expirado" }),
      record({ status: "aguardando_manifestacao" }),
    ]);
    expect(result.expiredWithoutManifestation).toBe(2);
  });

  it("sem amostra, não devolve média", () => {
    const result = stageTimings([record()]);
    expect(result.averageHoursToManifest).toBeNull();
    expect(result.manifestSample).toBe(0);
  });
});
