/**
 * Estatísticas de uso do módulo — o instrumento de medição do MVP.
 *
 * Responde às perguntas do ciclo "implementar → utilizar → observar →
 * medir → melhorar": quais motivos aparecem mais, quais campos são pouco
 * usados e quais etapas estão demorando. Tudo puro e testável: a página
 * apenas exibe o que estas funções calculam.
 */
import type { FollowUpStatus, FollowUpType } from "./followUp";

export interface StatsRecord {
  id: string;
  type: FollowUpType;
  status: FollowUpStatus;
  reasonText: string;
  reasonId: string | null;
  studentId: string;
  hasNotes: boolean;
  autoGenerated: boolean;
  occurredAt: string;
  manifestedAt: string | null;
  decidedAt: string | null;
}

export interface ReasonRanking {
  reasonText: string;
  type: FollowUpType;
  total: number;
  last7Days: number;
  last30Days: number;
  distinctStudents: number;
  lastUsedAt: string;
}

export interface FollowUpSummary {
  total: number;
  byType: Record<FollowUpType, number>;
  /** Quantos FO− foram lançados pela Coordenação (exclui os automáticos). */
  manualNegatives: number;
  /** Gerados pelo sistema por ausência de manifestação. */
  autoGenerated: number;
  /** Percentual de registros em que a observação complementar foi preenchida. */
  notesUsageRate: number | null;
}

const DAY_MS = 24 * 60 * 60 * 1000;

const EMPTY_BY_TYPE: Record<FollowUpType, number> = {
  fo_negativo: 0,
  fo_positivo: 0,
  saude: 0,
  missao: 0,
  administrativo: 0,
};

export function summarize(records: StatsRecord[]): FollowUpSummary {
  const byType = { ...EMPTY_BY_TYPE };
  let withNotes = 0;
  let autoGenerated = 0;
  let manualNegatives = 0;

  for (const record of records) {
    byType[record.type] += 1;
    if (record.hasNotes) withNotes += 1;
    if (record.autoGenerated) autoGenerated += 1;
    else if (record.type === "fo_negativo") manualNegatives += 1;
  }

  return {
    total: records.length,
    byType,
    manualNegatives,
    autoGenerated,
    notesUsageRate: records.length === 0 ? null : withNotes / records.length,
  };
}

/**
 * Ranking de motivos. É a base para decidir, com dado real, quais motivos
 * merecem virar atalho — não antes disso.
 */
export function rankReasons(
  records: StatsRecord[],
  now: Date = new Date(),
  limit = 15,
): ReasonRanking[] {
  const groups = new Map<string, ReasonRanking & { students: Set<string> }>();

  for (const record of records) {
    const key = `${record.type}::${record.reasonText.toLowerCase()}`;
    let group = groups.get(key);
    if (!group) {
      group = {
        reasonText: record.reasonText,
        type: record.type,
        total: 0,
        last7Days: 0,
        last30Days: 0,
        distinctStudents: 0,
        lastUsedAt: record.occurredAt,
        students: new Set<string>(),
      };
      groups.set(key, group);
    }

    const age = now.getTime() - new Date(record.occurredAt).getTime();
    group.total += 1;
    if (age <= 7 * DAY_MS) group.last7Days += 1;
    if (age <= 30 * DAY_MS) group.last30Days += 1;
    group.students.add(record.studentId);
    if (record.occurredAt > group.lastUsedAt) group.lastUsedAt = record.occurredAt;
  }

  return [...groups.values()]
    .map(({ students, ...rest }) => ({ ...rest, distinctStudents: students.size }))
    .sort((a, b) => {
      if (b.last30Days !== a.last30Days) return b.last30Days - a.last30Days;
      if (b.total !== a.total) return b.total - a.total;
      return b.lastUsedAt.localeCompare(a.lastUsedAt);
    })
    .slice(0, limit);
}

export interface StageTiming {
  /** Horas médias entre o registro e a manifestação do cadete. */
  averageHoursToManifest: number | null;
  manifestSample: number;
  /** Horas médias entre a manifestação e a decisão da Coordenação. */
  averageHoursToDecide: number | null;
  decideSample: number;
  /** FO− que venceram sem qualquer manifestação. */
  expiredWithoutManifestation: number;
}

function averageHours(values: number[]): number | null {
  if (values.length === 0) return null;
  return values.reduce((sum, value) => sum + value, 0) / values.length / (60 * 60 * 1000);
}

/**
 * Onde o fluxo está travando. Sempre acompanhado do tamanho da amostra:
 * com poucas semanas de uso, uma média de 3 registros não decide nada.
 */
export function stageTimings(records: StatsRecord[]): StageTiming {
  const toManifest: number[] = [];
  const toDecide: number[] = [];
  let expiredWithoutManifestation = 0;

  for (const record of records) {
    if (record.manifestedAt) {
      toManifest.push(
        new Date(record.manifestedAt).getTime() - new Date(record.occurredAt).getTime(),
      );
      if (record.decidedAt) {
        toDecide.push(
          new Date(record.decidedAt).getTime() - new Date(record.manifestedAt).getTime(),
        );
      }
    } else if (record.status === "prazo_expirado") {
      expiredWithoutManifestation += 1;
    }
  }

  return {
    averageHoursToManifest: averageHours(toManifest),
    manifestSample: toManifest.length,
    averageHoursToDecide: averageHours(toDecide),
    decideSample: toDecide.length,
    expiredWithoutManifestation,
  };
}
