/* eslint-disable @typescript-eslint/no-explicit-any */
import type { SupabaseClient } from "@supabase/supabase-js";
import type {
  FollowUpStatus,
  FollowUpType,
  PunishmentStatus,
  ReasonSuggestion,
} from "../domain/followUp";
import type { StatsRecord } from "../domain/statistics";

type Client = SupabaseClient<any, any, any>;

export interface StudentRef {
  id: string;
  warName: string;
  studentNumber: number | null;
  fullName: string;
}

export interface FollowUpListItem {
  id: string;
  type: FollowUpType;
  status: FollowUpStatus;
  reasonText: string;
  notes: string | null;
  occurredAt: string;
  deadlineAt: string | null;
  autoGenerated: boolean;
  createdByName: string | null;
  student: StudentRef;
  punishmentStatus: PunishmentStatus | null;
  hasManifestation: boolean;
}

export interface FollowUpDetail extends FollowUpListItem {
  classId: string | null;
  originRecordId: string | null;
  manifestation: {
    id: string;
    body: string;
    submittedAt: string;
  } | null;
  decision: {
    outcome: "deferido" | "indeferido";
    rationale: string | null;
    decidedByName: string | null;
    decidedAt: string;
  } | null;
  punishment: {
    id: string;
    punishmentText: string;
    instructions: string | null;
    status: PunishmentStatus;
    statusNotes: string | null;
    completedAt: string | null;
  } | null;
  attachments: {
    id: string;
    originalFilename: string;
    mimeType: string;
    storagePath: string;
  }[];
  events: {
    id: string;
    eventType: string;
    description: string | null;
    actorName: string | null;
    createdAt: string;
  }[];
}

export function studentLabel(student: {
  warName: string;
  studentNumber: number | null;
}): string {
  return student.studentNumber
    ? `${student.warName} — ${String(student.studentNumber).padStart(2, "0")}`
    : student.warName;
}

function mapStudent(row: any): StudentRef {
  return {
    id: row?.id ?? "",
    warName: row?.war_name ?? "ALUNO",
    studentNumber: row?.student_number ?? null,
    fullName: row?.full_name ?? "",
  };
}

const LIST_SELECT = `
  id, type, status, reason_text, notes, occurred_at, deadline_at,
  auto_generated, created_by_name,
  student:students!follow_up_records_student_id_fkey ( id, war_name, student_number, full_name ),
  follow_up_punishments ( status ),
  follow_up_manifestations ( id )
`;

function mapListItem(row: any): FollowUpListItem {
  const punishment = Array.isArray(row.follow_up_punishments)
    ? row.follow_up_punishments[0]
    : row.follow_up_punishments;
  const manifestation = Array.isArray(row.follow_up_manifestations)
    ? row.follow_up_manifestations[0]
    : row.follow_up_manifestations;

  return {
    id: row.id,
    type: row.type,
    status: row.status,
    reasonText: row.reason_text,
    notes: row.notes ?? null,
    occurredAt: row.occurred_at,
    deadlineAt: row.deadline_at ?? null,
    autoGenerated: Boolean(row.auto_generated),
    createdByName: row.created_by_name ?? null,
    student: mapStudent(row.student),
    punishmentStatus: punishment?.status ?? null,
    hasManifestation: Boolean(manifestation?.id),
  };
}

/**
 * Dispara a rotina de expiração de prazo antes de qualquer listagem da
 * Coordenação. Idempotente — o cron diário faz o mesmo, esta chamada
 * só garante que a central esteja correta mesmo sem o cron.
 */
export async function expireDeadlines(supabase: Client): Promise<number> {
  const { data, error } = await supabase.rpc("expire_follow_up_deadlines");
  if (error) return 0;
  return typeof data === "number" ? data : 0;
}

export async function listFollowUps(
  supabase: Client,
  options: { statuses?: FollowUpStatus[]; studentId?: string; limit?: number } = {},
): Promise<FollowUpListItem[]> {
  let query = supabase
    .from("follow_up_records")
    .select(LIST_SELECT)
    .order("occurred_at", { ascending: false })
    .limit(options.limit ?? 200);

  if (options.statuses?.length) query = query.in("status", options.statuses);
  if (options.studentId) query = query.eq("student_id", options.studentId);

  const { data, error } = await query;
  if (error) return [];
  return (data ?? []).map(mapListItem);
}

export async function countByStatus(
  supabase: Client,
): Promise<Record<FollowUpStatus, number>> {
  const { data } = await supabase.from("follow_up_records").select("status");
  const counts = {} as Record<FollowUpStatus, number>;
  for (const row of (data ?? []) as { status: FollowUpStatus }[]) {
    counts[row.status] = (counts[row.status] ?? 0) + 1;
  }
  return counts;
}

export async function fetchFollowUp(
  supabase: Client,
  id: string,
): Promise<FollowUpDetail | null> {
  const { data, error } = await supabase
    .from("follow_up_records")
    .select(
      `
      id, type, status, reason_text, notes, occurred_at, deadline_at, class_id,
      auto_generated, created_by_name, origin_record_id,
      student:students!follow_up_records_student_id_fkey ( id, war_name, student_number, full_name ),
      follow_up_manifestations ( id, body, submitted_at ),
      follow_up_decisions ( outcome, rationale, decided_by_name, decided_at ),
      follow_up_punishments ( id, punishment_text, instructions, status, status_notes, completed_at ),
      follow_up_attachments ( id, original_filename, mime_type, storage_path ),
      follow_up_events ( id, event_type, description, actor_name, created_at )
    `,
    )
    .eq("id", id)
    .maybeSingle();

  if (error || !data) return null;

  const row = data as any;
  const manifestation = Array.isArray(row.follow_up_manifestations)
    ? row.follow_up_manifestations[0]
    : row.follow_up_manifestations;
  const decision = Array.isArray(row.follow_up_decisions)
    ? row.follow_up_decisions[0]
    : row.follow_up_decisions;
  const punishment = Array.isArray(row.follow_up_punishments)
    ? row.follow_up_punishments[0]
    : row.follow_up_punishments;

  return {
    ...mapListItem({ ...row, follow_up_punishments: punishment, follow_up_manifestations: manifestation }),
    classId: row.class_id ?? null,
    originRecordId: row.origin_record_id ?? null,
    manifestation: manifestation
      ? {
          id: manifestation.id,
          body: manifestation.body,
          submittedAt: manifestation.submitted_at,
        }
      : null,
    decision: decision
      ? {
          outcome: decision.outcome,
          rationale: decision.rationale ?? null,
          decidedByName: decision.decided_by_name ?? null,
          decidedAt: decision.decided_at,
        }
      : null,
    punishment: punishment
      ? {
          id: punishment.id,
          punishmentText: punishment.punishment_text,
          instructions: punishment.instructions ?? null,
          status: punishment.status,
          statusNotes: punishment.status_notes ?? null,
          completedAt: punishment.completed_at ?? null,
        }
      : null,
    attachments: (row.follow_up_attachments ?? []).map((item: any) => ({
      id: item.id,
      originalFilename: item.original_filename,
      mimeType: item.mime_type,
      storagePath: item.storage_path,
    })),
    events: (row.follow_up_events ?? [])
      .map((item: any) => ({
        id: item.id,
        eventType: item.event_type,
        description: item.description ?? null,
        actorName: item.actor_name ?? null,
        createdAt: item.created_at,
      }))
      .sort((a: any, b: any) => a.createdAt.localeCompare(b.createdAt)),
  };
}

/** Motivos já cadastrados — alimentam o autocomplete do registro. */
export async function listReasonSuggestions(
  supabase: Client,
  kind?: FollowUpType,
): Promise<Record<string, ReasonSuggestion[]>> {
  let query = supabase
    .from("fo_reasons")
    .select("id, kind, label, usage_count, last_used_at")
    .eq("active", true)
    .order("usage_count", { ascending: false })
    .limit(400);

  if (kind) query = query.eq("kind", kind);

  const { data } = await query;
  const grouped: Record<string, ReasonSuggestion[]> = {};
  for (const row of (data ?? []) as any[]) {
    (grouped[row.kind] ??= []).push({
      id: row.id,
      label: row.label,
      usageCount: row.usage_count ?? 0,
      lastUsedAt: row.last_used_at ?? null,
    });
  }
  return grouped;
}

/** Punições já utilizadas — alimentam o autocomplete da decisão. */
export async function listPunishmentSuggestions(
  supabase: Client,
): Promise<ReasonSuggestion[]> {
  const { data } = await supabase
    .from("punishment_options")
    .select("id, label, usage_count, last_used_at")
    .eq("active", true)
    .order("usage_count", { ascending: false })
    .limit(200);

  return (data ?? []).map((row: any) => ({
    id: row.id,
    label: row.label,
    usageCount: row.usage_count ?? 0,
    lastUsedAt: row.last_used_at ?? null,
  }));
}

/**
 * Linhas cruas para a tela de estatísticas. O cálculo fica no domínio
 * (`statistics.ts`) — aqui só se busca o dado.
 *
 * Lê das tabelas base, protegidas por RLS: a Coordenação enxerga a turma
 * inteira; qualquer outro perfil enxergaria apenas o que lhe cabe.
 */
export async function fetchStatsRecords(
  supabase: Client,
  limit = 2000,
): Promise<StatsRecord[]> {
  const { data, error } = await supabase
    .from("follow_up_records")
    .select(
      `
      id, type, status, reason_text, reason_id, student_id, notes,
      auto_generated, occurred_at,
      follow_up_manifestations ( submitted_at ),
      follow_up_decisions ( decided_at )
    `,
    )
    .order("occurred_at", { ascending: false })
    .limit(limit);

  if (error) return [];

  return (data ?? []).map((row: any) => {
    const manifestation = Array.isArray(row.follow_up_manifestations)
      ? row.follow_up_manifestations[0]
      : row.follow_up_manifestations;
    const decision = Array.isArray(row.follow_up_decisions)
      ? row.follow_up_decisions[0]
      : row.follow_up_decisions;

    return {
      id: row.id,
      type: row.type,
      status: row.status,
      reasonText: row.reason_text,
      reasonId: row.reason_id ?? null,
      studentId: row.student_id,
      hasNotes: Boolean(row.notes && String(row.notes).trim().length > 0),
      autoGenerated: Boolean(row.auto_generated),
      occurredAt: row.occurred_at,
      manifestedAt: manifestation?.submitted_at ?? null,
      decidedAt: decision?.decided_at ?? null,
    };
  });
}

/** Situação atual das punições — complementa a leitura do ciclo. */
export async function countPunishmentsByStatus(
  supabase: Client,
): Promise<Record<PunishmentStatus, number>> {
  const { data } = await supabase.from("follow_up_punishments").select("status");
  const counts = {} as Record<PunishmentStatus, number>;
  for (const row of (data ?? []) as { status: PunishmentStatus }[]) {
    counts[row.status] = (counts[row.status] ?? 0) + 1;
  }
  return counts;
}
