import Link from "next/link";
import { notFound } from "next/navigation";
import { Paperclip } from "lucide-react";
import { requireRole } from "@/components/app/RoleGuard";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { SectionEyebrow } from "@/components/ui/SectionEyebrow";
import { DeadlineCountdown } from "@/components/app/followup/DeadlineCountdown";
import {
  PunishmentBadge,
  StatusBadge,
  TypeBadge,
} from "@/components/app/followup/FollowUpBadges";
import { DecisionForm } from "@/components/app/followup/DecisionForm";
import { PunishmentStatusForm } from "@/components/app/followup/PunishmentStatusForm";
import { CancelFollowUpForm } from "@/components/app/followup/CancelFollowUpForm";
import { FollowUpTimeline } from "@/components/app/followup/FollowUpTimeline";
import { formatDateTime } from "@/components/app/followup/format";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import {
  fetchFollowUp,
  listPunishmentSuggestions,
  studentLabel,
} from "@/modules/cadet-followup/infrastructure/queries";
import { FOLLOW_UP_TYPE_FULL_LABELS } from "@/modules/cadet-followup/domain/followUp";

export const metadata = { title: "Registro de acompanhamento" };
export const dynamic = "force-dynamic";

export default async function AcompanhamentoDetalhePage({
  params,
}: {
  params: { id: string };
}) {
  await requireRole("coordenacao");
  const supabase = createSupabaseServerClient();

  const record = await fetchFollowUp(supabase, params.id);
  if (!record) notFound();

  const punishmentSuggestions = await listPunishmentSuggestions(supabase);

  const attachments = await Promise.all(
    record.attachments.map(async (attachment) => {
      const { data } = await supabase.storage
        .from("followup-attachments")
        .createSignedUrl(attachment.storagePath, 60 * 10);
      return { ...attachment, url: data?.signedUrl ?? null };
    }),
  );

  const awaitingDecision =
    record.status === "aguardando_analise" || record.status === "prazo_expirado";
  const isOpen = !["deferido", "indeferido", "concluido", "cancelado"].includes(record.status);

  return (
    <div className="mx-auto max-w-2xl space-y-5">
      <div>
        <Link
          href="/coordenacao/acompanhamento"
          className="text-sm text-muted-foreground hover:underline"
        >
          ← Central de acompanhamento
        </Link>
      </div>

      <header className="space-y-2">
        <SectionEyebrow>{FOLLOW_UP_TYPE_FULL_LABELS[record.type]}</SectionEyebrow>
        <h1 className="font-display text-2xl font-bold uppercase tracking-[0.02em]">
          <Link
            href={`/coordenacao/alunos/${record.student.id}?tab=acompanhamento`}
            className="hover:underline"
          >
            {studentLabel(record.student)}
          </Link>
        </h1>
        <div className="flex flex-wrap items-center gap-1.5">
          <TypeBadge type={record.type} />
          <StatusBadge status={record.status} />
          {record.punishment && <PunishmentBadge status={record.punishment.status} />}
        </div>
      </header>

      <Card>
        <CardHeader>
          <CardTitle>Fato registrado</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-base font-semibold text-foreground">{record.reasonText}</p>
          {record.notes && (
            <p className="whitespace-pre-wrap text-sm text-muted-foreground">{record.notes}</p>
          )}
          <dl className="grid grid-cols-2 gap-3 border-t border-border pt-3 text-sm">
            <div>
              <dt className="text-xs uppercase tracking-wider text-muted-foreground">
                Data e hora
              </dt>
              <dd className="num-mono">{formatDateTime(record.occurredAt)}</dd>
            </div>
            <div>
              <dt className="text-xs uppercase tracking-wider text-muted-foreground">
                Responsável
              </dt>
              <dd>{record.createdByName ?? "—"}</dd>
            </div>
          </dl>

          {record.status === "aguardando_manifestacao" && record.deadlineAt && (
            <DeadlineCountdown deadline={record.deadlineAt} />
          )}

          {record.autoGenerated && record.originRecordId && (
            <p className="rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-800 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-200">
              Registro gerado automaticamente pela ausência de manifestação.{" "}
              <Link
                href={`/coordenacao/acompanhamento/${record.originRecordId}`}
                className="font-semibold underline"
              >
                Ver o FO de origem
              </Link>
            </p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Manifestação do cadete</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {record.manifestation ? (
            <>
              <p className="whitespace-pre-wrap text-sm text-foreground">
                {record.manifestation.body}
              </p>
              <p className="text-xs text-muted-foreground">
                Enviada em {formatDateTime(record.manifestation.submittedAt)}
              </p>
              {attachments.length > 0 && (
                <ul className="space-y-1 border-t border-border pt-3">
                  {attachments.map((attachment) => (
                    <li key={attachment.id}>
                      <a
                        href={attachment.url ?? "#"}
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-2 text-sm text-foreground hover:underline"
                      >
                        <Paperclip className="h-4 w-4 shrink-0" aria-hidden />
                        {attachment.originalFilename}
                      </a>
                    </li>
                  ))}
                </ul>
              )}
            </>
          ) : record.status === "prazo_expirado" ? (
            <p className="text-sm text-destructive">
              Prazo encerrado — manifestação não apresentada.
            </p>
          ) : (
            <p className="text-sm text-muted-foreground">
              Ainda não apresentada pelo cadete.
            </p>
          )}
        </CardContent>
      </Card>

      {awaitingDecision && (
        <Card>
          <CardHeader>
            <CardTitle>Análise da Coordenação</CardTitle>
          </CardHeader>
          <CardContent>
            <DecisionForm recordId={record.id} punishmentSuggestions={punishmentSuggestions} />
          </CardContent>
        </Card>
      )}

      {record.decision && (
        <Card>
          <CardHeader>
            <CardTitle>Decisão</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <p className="font-display text-base font-bold uppercase tracking-[0.06em]">
              {record.decision.outcome === "deferido" ? "Deferido" : "Indeferido"}
            </p>
            {record.decision.rationale && (
              <p className="whitespace-pre-wrap text-muted-foreground">
                {record.decision.rationale}
              </p>
            )}
            <p className="text-xs text-muted-foreground">
              {record.decision.decidedByName ?? "Coordenação"} ·{" "}
              {formatDateTime(record.decision.decidedAt)}
            </p>
          </CardContent>
        </Card>
      )}

      {record.punishment && (
        <Card>
          <CardHeader>
            <CardTitle>Punição e cumprimento</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <p className="text-base font-semibold">{record.punishment.punishmentText}</p>
              {record.punishment.instructions && (
                <p className="whitespace-pre-wrap text-sm text-muted-foreground">
                  {record.punishment.instructions}
                </p>
              )}
              <PunishmentBadge status={record.punishment.status} />
              {record.punishment.statusNotes && (
                <p className="text-sm text-muted-foreground">{record.punishment.statusNotes}</p>
              )}
            </div>
            <div className="border-t border-border pt-4">
              <PunishmentStatusForm recordId={record.id} current={record.punishment.status} />
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Histórico do registro</CardTitle>
        </CardHeader>
        <CardContent>
          <FollowUpTimeline events={record.events} />
        </CardContent>
      </Card>

      {isOpen && <CancelFollowUpForm recordId={record.id} />}
    </div>
  );
}
